Update Base64.lua
Sleitnick/AeroGameFramework pull request #204
Opened 2020-09-07 02:41 UTC by howmanysmall

Optimized a good bit. It's around 10%+ faster.

2020-11-23 15:13 UTC, Sleitnick requested changes
Can you switch `Decode` and `Encode` back to using `:` notation instead of `.`? It just makes the code more confusing to read. The other changes look good.

2020-11-23 18:55 UTC, howmanysmall commented
Yeah, I can do that since Selene 0.9.2 changed the problem so it doesn't freak out by default.

2020-12-17 01:13 UTC, fre3d0m1 approved these changes

2020-12-18 17:36 UTC, Sleitnick approved these changes

2020-12-18 17:36 UTC, merged